# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:http://localhost:3000"
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
detailed-logging: true
should-log-all: true
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
  user:     "_env:PGUSER:taplike"
  password: "_env:PGPASS:taplike"
  host:     "_env:POSTGRES_HOST:localhost"
  port:     "_env:PGPORT:5432"
  database: "_env:PGDATABASE:taplike"
  poolsize: "_env:PGPOOLSIZE:10"

twitter:
  accessKey:      "_env:TWITTER_ACCESS_KEY:4148784514-UJWayNsMMrHUaFYQu9KjiKoE9BMimidVhrvxJqV"
  accessSecret:   "_env:TWITTER_ACCESS_SECRET:0dfZvs2dCNCjVCLftq2xP8aYjkAPrIRd5hnZS2OoxYSAr"
  consumerKey:    "_env:TWITTER_CONSUMER_KEY:jQLyz9tL4N1dH3JgoRjt7oXJd"
  consumerSecret: "_env:TWITTER_CONSUMER_SECRET:xcKEmKUQb216M8VZ0rZx0zYd2jshBV7w4vZd9nBFZga16c09zx"

redis:
  redisHost: "_env:REDIS_HOST:localhost"

copyright: Insert copyright statement here
analytics: UA-71422008-1
