api:
  dockerfile: Dockerfile
  build: .
  expose:
   - "3000"
  volumes:
   - .:/code
  net: "host"
  ports:
   - "3000:3000"
  links:
   - postgres
   - redis
  environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
  stdin_open: true
postgres:
  image: postgres
  ports:
   - "5432:5432"
redis:
  image: redis
