flags:
  chat-app:
    library-only: false
    dev: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- stm-lifted-0.1.0.0
- twitter-conduit-0.1.1.1
- twitter-types-0.7.1.1
- twitter-types-lens-0.7.1
- yesod-websockets-0.2.4
- pwstore-fast-2.4.4
flags:
  twitter-types:
    time15: true
resolver: lts-3.11
